spring:
  application:
    name: flight-booking-system # The name of the Spring Boot application

  datasource:
    url: jdbc:mysql://localhost/flight_booking # JDBC URL for connecting to the MySQL database
    username: root # Username for accessing the MySQL database
    password: Account@name18 # Password for the MySQL database

  jpa:
    hibernate:
      ddl-auto: update # Specifies the strategy for schema generation. 'update' will update the database schema based on the entity definitions.
      show-sql: true # Enables logging of SQL statements executed by Hibernate
